export default animations = {
    "cloud-disconnection": require('../assets/lotties/cloud-disconnection.json'),
    "question-mark": require('../assets/lotties/question-mark.json'),
    "loading-jumping-ball": require('../assets/lotties/loading-jumping-ball.json'),
    "empty-box": require('../assets/lotties/empty-box.json'),
    "empty-gabinete": require('../assets/lotties/empty-gabinete.json'),
    "falling-empty-box": require('../assets/lotties/falling-empty-box.json'),
    "error-tv": require('../assets/lotties/error-tv.json'),
    "scanning": require('../assets/lotties/scanning.json'),
    "user-scanning": require('../assets/lotties/user-scanning.json'),
    "user-scanning2": require('../assets/lotties/user-scanning2.json'),
    "role-models": require('../assets/lotties/role-models.json'),
    "mentors": require('../assets/lotties/mentors.json'),
    "search-users": require('../assets/lotties/search-users.json'),
    "minnion-looking": require('../assets/lotties/minnion-looking.json'),
    "searching-around": require('../assets/lotties/searching-around.json'),
};
