const actions = {
  ADD_ARRAY_ELEMENT: 'events/ADD_ARRAY_ELEMENT',
  FIND_LOCATION: 'events/FIND_LOCATION',
  CREATE_EVENT: 'events/CREATE_EVENT',
  UPDATE_EVENT: 'events/UPDATE_EVENT',
  DELETE_EVENT: 'events/DELETE_EVENT',
  CREATE_TASK: 'events/CREATE_TASK',
  EDIT_TASK: 'events/EDIT_TASK',
  COMPLETE_TASK: 'events/COMPLETE_TASK',
  DELETE_TASK: 'events/DELETE_TASK',
  GET_EVENT_TASK: 'events/GET_EVENT_TASK',
  GET_EVENT_TASKS: 'events/GET_EVENT_TASKS',
  DELETE_ARRAY_ELEMENT: 'events/DELETE_ARRAY_ELEMENT',
  GET_EVENTS: 'events/GET_EVENTS',
  GET_EVENT: 'events/GET_EVENT',
  GET_EVENT_ATENDEES: 'events/GET_EVENT_ATENDEES',
  RESET_APP: 'RESET_APP',
  SET_STATE: 'events/SET_STATE',
}

export default actions
