const actions = {
  ADD_ARRAY_ELEMENT: 'events/ADD_ARRAY_ELEMENT',
  FIND_LOCATION: 'events/FIND_LOCATION',
  CREATE_EVENT: 'events/CREATE_EVENT',
  DELETE_ARRAY_ELEMENT: 'events/DELETE_ARRAY_ELEMENT',
  GET_EVENTS: 'events/GET_EVENTS',
  GET_EVENT: 'events/GET_EVENT',
  GET_EVENT_ATTENDEES: 'events/GET_EVENT_ATTENDEES',
  GET_EVENT_ATTENDEES: 'events/GET_EVENT_ATTENDEES',
  RESET_APP: 'RESET_APP',
  SET_STATE: 'events/SET_STATE',
}

export default actions
