const actions = {
  RESET_APP: 'RESET_APP',
  SET_STATE: 'session/SET_STATE',
  SEARCH_USERS: 'session/SEARCH_USERS',
  GET_USER_INVITATIONS: 'session/GET_USER_INVITATIONS',
  GET_USER_EVENTS: 'session/GET_USER_EVENTS',
  ACCEPT_EVENT_INVITATION: 'session/ACCEPT_EVENT_INVITATION',
  ADD_ARRAY_ELEMENT: 'session/ADD_ARRAY_ELEMENT',
  DELETE_ARRAY_ELEMENT: 'session/DELETE_ARRAY_ELEMENT',
  LOGIN: 'session/LOGIN',
  UPDATE_PROFILE: 'session/UPDATE_PROFILE',
  REGISTER: 'session/REGISTER',
  CHANGE_CURRENT_GROUP: 'session/CHANGE_CURRENT_GROUP',
  LOAD_CURRENT_ACCOUNT: 'session/LOAD_CURRENT_ACCOUNT',
  LOGOUT: 'session/LOGOUT',
  UNAUTH_USER: 'session/UNAUTH_USER'
}

export default actions
