const actions = {
  SET_STATE: 'mentors/SET_STATE',
  ADD_ARRAY_ELEMENT: 'mentors/ADD_ARRAY_ELEMENT',
  DELETE_ARRAY_ELEMENT: 'mentors/DELETE_ARRAY_ELEMENT',
  REPLACE_ARRAY_ELEMENT: 'mentors/REPLACE_ARRAY_ELEMENT',
  GET_MENTORS: 'mentors/GET_MENTORS',
  GET_MENTOR_ACTIVITIES: 'mentors/GET_MENTOR_ACTIVITIES',
  GET_ACTIVITY_AVAILABILITIES: 'mentors/GET_ACTIVITY_AVAILABILITIES',
  SEARCH_ACTIVITIES: 'mentors/SEARCH_ACTIVITIES',
  CREATE_ACTIVITY: 'mentors/CREATE_ACTIVITY',
  CREATE_AVAILABILITY: 'mentors/CREATE_AVAILABILITY',
  UPDATE_ACTIVITY: 'mentors/UPDATE_ACTIVITY',
  UPDATE_AVAILABILITY: 'mentors/UPDATE_AVAILABILITY',
  DELETE_ACTIVITY: 'mentors/DELETE_ACTIVITY',
  DELETE_AVAILABILITY: 'mentors/DELETE_AVAILABILITY',
  RESET_APP: 'RESET_APP',
}

export default actions
