const actions = {
  RESET_APP: 'RESET_APP',
  GET_LOCATION: 'trip/GET_LOCATION',
  CREATE_TRIP: 'trip/CREATE_TRIP',
  ADD_LOCATION: 'trip/ADD_LOCATION',
  POP_LOCATION: 'trip/POP_LOCATION',
  CREATE_LOCATION: 'trip/CREATE_LOCATION',
  DELETE_LOCATION: 'trip/DELETE_LOCATION',
  GET_LOCATIONS: 'trip/GET_LOCATIONS',
  SET_STATE: 'trip/SET_STATE',
  SET_LOCATION_STATE: 'trip/SET_LOCATION_STATE',
}

export default actions
