const actions = {
  RESET_APP: 'RESET_APP',
  GET_GROUP: 'groups/GET_GROUP',
  GET_GROUPS: 'groups/GET_GROUPS',
  CONCAT_GROUPS: 'groups/CONCAT_GROUPS',
  GET_GROUP_MEMBERS: 'groups/GET_GROUP_MEMBERS',
  GET_GROUP_CANDIDATES: 'groups/GET_GROUP_CANDIDATES',
  INCREASE_PRIVILEGES: 'groups/INCREASE_PRIVILEGES',
  DECREASE_PRIVILEGES: 'groups/DECREASE_PRIVILEGESS',
  CREATE_GROUP: 'groups/CREATE_GROUP',
  ADD_GROUP_MEMBER: 'groups/ADD_GROUP_MEMBER',
  ADD_GROUP_ADMIN: 'groups/ADD_GROUP_ADMIN',
  DELETE_GROUP_MEMBER: 'groups/DELETE_GROUP_MEMBER',
  DELETE_GROUP_ADMIN: 'groups/DELETE_GROUP_ADMIN',
  DELETE_GROUP: 'groups/DELETE_GROUP',
  SET_STATE: 'groups/SET_STATE',
  SET_GROUP_STATE: 'groups/SET_GROUP_STATE',
}

export default actions
