const actions = {
  SET_STATE: 'roleModels/SET_STATE',
  ADD_ARRAY_ELEMENT: 'roleModels/ADD_ARRAY_ELEMENT',
  DELETE_ARRAY_ELEMENT: 'roleModels/DELETE_ARRAY_ELEMENT',
  REPLACE_ARRAY_ELEMENT: 'roleModels/REPLACE_ARRAY_ELEMENT',
  GET_ROLE_MODELS: 'roleModels/GET_ROLE_MODELS',
  GET_ROLE_MODEL_POSTS: 'roleModels/GET_ROLE_MODEL_POSTS',
  GET_ROLE_MODELS_POSTS: 'roleModels/GET_ROLE_MODELS_POSTS',
  CREATE_POST: 'roleModels/CREATE_POST',
  UPDATE_POST: 'roleModels/UPDATE_POST',
  DELETE_POST: 'roleModels/DELETE_POST',
  RESET_APP: 'RESET_APP',
}

export default actions
